name: "CI"

on:
  workflow_dispatch:
  push:
   branches:
     - 'main'
     - 'releases/**'
     - 'features/**'
concurrency:
  group: pipeline-${{ github.head_ref || github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  get-version:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.json-version-parser.outputs.releaseVersion }}
      assemblyVersion: ${{ steps.json-version-parser.outputs.assemblyVersion }}
    env:
      INFO_PATH: ./src/BubbleBuffs.Multiplayer/Info.json
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Read current version
        id: json-version-parser
        run: |
          baseFullVersion=$(jq -r '.version' "${{ env.INFO_PATH }}")
          echo "Info Json Version: $baseFullVersion"
          majorMinor="${baseFullVersion%.*}"
          echo "MajorMinorVersion: $majorMinor"
          
          # github run offset so the next run becomes version 1
          baseRun=21
          echo "GitHub Run: ${{ github.run_number }}"
          versionRunNumber=$(( ${{ github.run_number }} - baseRun ))
          versionRunNumber=$(( versionRunNumber < 0 ? 0 : versionRunNumber ))
          echo "Version Run: $versionRunNumber"
          
          assemblyVersion="${majorMinor}.${versionRunNumber}"
          releaseVersion="$assemblyVersion"
          if [[ "${{ github.ref_name }}" == features/* ]]; then
            releaseVersion="${releaseVersion}-alpha"
          fi

          echo "Release Version: $releaseVersion"
          echo "releaseVersion=$releaseVersion" >> "$GITHUB_OUTPUT"
          echo "Assembly Version: $assemblyVersion"
          echo "assemblyVersion=$assemblyVersion" >> "$GITHUB_OUTPUT"

  build:
    needs: [get-version]
    timeout-minutes: 10
    env:
      WOTR_PATH: ../../libs
      BUILD_PATH: ".\\src\\BubbleBuffs.Multiplayer\\bin\\Release\\net481"
      RELEASE_OUTPUT_PATH: ".\\__releases\\BubbleBuffs.Multiplayer"
      CURRENT_VERSION: ${{needs.get-version.outputs.releaseVersion}}
      ASSEMBLY_VERSION: ${{needs.get-version.outputs.assemblyVersion}}
    runs-on: windows-latest

    steps:
      - name: Verify version
        if: ${{ env.CURRENT_VERSION == '' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Unable to parse version');
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Checkout libs
        uses: actions/checkout@v4
        with:
          repository: fl01/pathfinder-wotr-libs
          token: ${{ secrets.WOTR_LIBS_TOKEN }}
          path: wotr-libs
      - name: Copy libs
        run: |
          xcopy /E /I /Y "wotr-libs\bubblebuffslibs\libs" "libs\"
      - name: Build
        run: dotnet build ./src /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} --configuration Release
      - name: Update Info.json
        run: |
          echo $(jq '.version="${{ env.CURRENT_VERSION }}"' "${{ env.BUILD_PATH }}\Info.json") > "${{ env.BUILD_PATH }}\Info.json"
      - name: Prepare Release
        run: |
          xcopy /q /y "${{ env.BUILD_PATH }}\Info.json" "${{ env.RELEASE_OUTPUT_PATH }}\*"
          xcopy /q /y "${{ env.BUILD_PATH }}\BubbleBuffs.Multiplayer*.dll" "${{ env.RELEASE_OUTPUT_PATH }}\*"
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: bubblebuffs-multiplayer-${{ env.CURRENT_VERSION }}
          path: "${{ github.workspace }}/__releases/"
          retention-days: 3

  tag-release:
    if: ${{ startsWith(github.ref, 'refs/heads/releases/') }}
    needs: [build, get-version]
    timeout-minutes: 10
    env:
      CURRENT_VERSION: ${{needs.get-version.outputs.releaseVersion}}
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.CURRENT_VERSION }}"
          message: "Release ${{ env.CURRENT_VERSION }}"

  create-draft-release:
    if: ${{ startsWith(github.ref, 'refs/heads/releases/') }}
    needs: [build, get-version, tag-release]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    env:
      CURRENT_VERSION: ${{ needs.get-version.outputs.releaseVersion }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bubblebuffs-multiplayer-${{ env.CURRENT_VERSION }}
          path: artifacts
      # unfortunately, download-artifact automatically extracts the artifact, even when it's already a ZIP, and there is no way to disable this :(
      - name: Repack
        run: |
          mkdir -p artifacts/__repack
          cd artifacts
          zip -r "__repack/bubblebuffs-multiplayer-${{ env.CURRENT_VERSION }}.zip" BubbleBuffs.Multiplayer
      - name: Create draft release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.CURRENT_VERSION }}
          name: ${{ env.CURRENT_VERSION }}
          draft: true
          generate_release_notes: false
          files: artifacts/__repack/*.zip
